### ISSUE TITLE
Sugestion: Support ajax data source?

### ISSUE THREAD

**Issue by Gavin-Gong** [jvilk/MakeTypes#12]
In some scenarios, Maybe I just want to get json from ajax request instead of local json file.
I hope MakeTypes can auto detect data source. if data source is a url, then we can request the url and parse response

the usage maybe look like below:
``` bash
make_types -i interface.ts https://example.com/data.json RootName
```

sorry for my poor english, really hope you can understand. thx for your awesome repo.

**Comment by jvilk** [comment]
Thanks for the kind words! I think this is better suited to other tools, like `wget` or `curl`, that already do a fantastic job of fetching files from URLs / API endpoints.
