### ISSUE TITLE
Suggestion: io-ts proxy output mode

### ISSUE THREAD

**Issue by stereobooster** [jvilk/MakeTypes#6]
https://github.com/gcanti/io-ts

**Comment by jvilk** [comment]
Thanks for the tip, but I would like to avoid runtime dependencies on external libraries. If `io-ts` produced TypeScript code statically/offline to verify specific types, I might be more tempted to use it. However, it instead dynamically constructs type-checking code at runtime, requiring the library's presence.

Perhaps this could be a third output mode? I'm willing to accept a PR.

**Comment by stereobooster** [comment]
io-ts is dynamic type system, but it is compatible with TypeScript/Flow e.g. you declare

```javascript
const Person = t.interface({
  name: t.string,
  age: t.number
})
```

but TypeScript/Flow can get static types out of it

```typescript
type IPerson = t.TypeOf<typeof Person>

// same as
type IPerson = {
  name: string,
  age: number
}
```

And it has `Either` support built-in, so it is pretty close to Elm `Json.Decode` semantics e.g. http://eeue56.github.io/json-to-elm/

> Perhaps this could be a third output mode? 

Yes. I meant it to be one of the options. DIdn't meant completely to switch to it
