### ISSUE TITLE
Can't copy output text

### ISSUE THREAD

**Issue by thedewpoint** [jvilk/MakeTypes#7]
I love this tool and use it often. Usually when I convert the JSON to the interface I just download it, but I've been doing it so often and it's getting annoying. I really just want to be able to copy and paste the output text,but it doesn't work that way.

**Comment by eug48** [comment]
You could run the tool locally and copy to clipboard by piping to e.g. clip.exe (on Windows run e.g. `make_types -p proxies.ts samples.json RootName && type proxies.ts | clip.exe`).

The web interface could also be enhanced to use the JavaScript clipboard API.

**Comment by jvilk** [comment]
Glad to hear that the tool is useful for you! I can see about adding a copy button to the web interface.

**Comment by jvilk** [comment]
I have added a 'copy to clipboard' button to the web interface! Try it out and let me know if you have any issues. I'm using clipboard.js, so it should work in all modern browsers.
